### ISSUE TITLE
How can I deploy this?

### ISSUE THREAD

**Issue by tfreiling** [SpectoLabs/hoverfly-java-grpc#1]
Does this support deploying hoverfly as a server?
If so, how could we deploy this in a docker container or helm chart like this: https://github.com/helm/charts#%EF%B8%8F-deprecation-and-archive-notice ?

**Comment by tommysitu** [comment]
this repo is only the java wrapper for Hoverfly-grpc binary. To deploy, you can create a Docker image to run the binary along with the license file and then deploy it via helm chart. you can find an example for the open-source hoverfly here: https://github.com/helm/charts/tree/master/incubator/hoverfly
